### ISSUE TITLE
Issue #1:  Analiza zahtjeva projekta

### ISSUE THREAD

**Issue by sdejana** [lukavidic/ColorSorter_C#1]
U okviru Issue #1 potrebno je:

- [x] Pobrojati zadane funkcionalnosti,
- [x] Razmotriti eventualna ograničenja ili moguće dodatne funkcionalnosti, a koje se nalaze u okviru zadanih,
- [x] Razložiti funkcionalnosti na niz manjih.

**Comment by sdejana** [comment]
Ocjena težine (1 - veoma lako, 10 - veoma teško):

**3**

**Comment by jelena0000** [comment]
Ocjena težine: 3

**Comment by bole188** [comment]
Ocjena težine: 4

**Comment by jelena0000** [comment]
Dokument je uspješno završen i predat u granu dev -> docs.
Utrošeno vrijeme za izradu: 45 min.
