### ISSUE TITLE
Issue #10: Analiza baterije

### ISSUE THREAD

**Issue by bole188** [lukavidic/ColorSorter_C#10]
U okviru Issue #10 pronaći bateriju koja zadovoljava zahtjeve napajanja sklopa i kućišta u kome će se nalaziti.

**Comment by jelena0000** [comment]
Ocjena težine:

4

**Comment by sdejana** [comment]
Ocjena težine:

**3**

**Comment by jelena0000** [comment]
Za ovaj projektni zadatak potrebne su nam baterije tipa AA od 1.5V (alkalne ili NiMH punjive) sa kapacitetom od 1000 do 2500 mAh. U poređenju sa AAA baterijama, AA baterije pružaju veći kapacitet i duže trajanje, što ih čini pogodnijim za uređaje sa većim energetskim zahtjevima. Preporučeni proizvođači su Duracell i Energizer.
