### ISSUE TITLE
Issue #13: Projektovanje sistema napajanja

### ISSUE THREAD

**Issue by sdejana** [lukavidic/ColorSorter_C#13]
Potrebno je:
- [x] Na osnovu utvrđenih naponskih nivoa iz #7  predložiti tip regulatora napona
- [ ] Projektovati šemu sa eksternim oscilatorima
- [ ] Utvrditi razliku između internog i eksternog oscilatora

**Comment by sdejana** [comment]
Ocjena težine:

**6**

**Comment by bole188** [comment]
6

**Comment by jelena0000** [comment]
Ocjena težine: 6

**Comment by sdejana** [comment]
Vrijeme provedeno pri radu (aktivno) : 180h.
