### ISSUE TITLE
Issue #3:  Evidentiranje potrebnih komponenata koje nisu dostupne u originalnom sklopu

### ISSUE THREAD

**Issue by sdejana** [lukavidic/ColorSorter_C#3]
U okviru Issue #3 potrebno je:

- [ ] Uporediti tražene zahtjeve sa mogućim funkcionalnostima trenutnog sklopa,
- [ ] Pobrojati potrebne komponente, a koje nisu trenutno dostupne u vidu liste komponenata,
- [ ] Detaljno istražiti optimalne komponente za implementaciju traženih funkcionalnosti.

**Napomena: **
Voditi računa o broju potrebnih komponenata i njihovoj potrošnosti.

**Comment by sdejana** [comment]
Ocjena težine (1 - veoma lako, 10 - veoma teško):

**4**

**Comment by bole188** [comment]
Ocjena težine: 4

**Comment by jelena0000** [comment]
Ocjena težine: 4

**Comment by bole188** [comment]
Utrošeno vrijeme: 112.5 min
