### ISSUE TITLE
Issue #6: Analiza RGB senzora i Wi-Fi modula

### ISSUE THREAD

**Issue by bole188** [lukavidic/ColorSorter_C#6]
U okviru Issue #6 potrebno je ispitati i dokumentovati modele prethodno navedenih komponenti.
_Zadatak je moguće obaviti nakon što dobijemo informaciju o modelima ovih komponenti_

- [x] Pronaći datasheets za obe komponente.
- [x] Utvrditi osnovne i potrebne podatke o komponentama.
- [x] Dodati dokumentaciju za komponente.

**Comment by sdejana** [comment]
Ocjena težine: 

**4**

**Comment by jelena0000** [comment]
Ocjena težine: 

4

**Comment by sdejana** [comment]
RGB senzor: Color 10 click
WiFi modul: ESP 8266 EX

**Comment by sdejana** [comment]
Vrijeme izrade: 110 minuta.
