### ISSUE TITLE
Issue #7: Analiza napajanja

### ISSUE THREAD

**Issue by bole188** [lukavidic/ColorSorter_C#7]
U okviru Issue #7 potrebno je istražiti koje napajanje najviše odgovara našem projektu i na koji način se ono integriše na pločicu. 
Nakon pronalaska odgovarajućeg napajanja dokumentovati isti i objasniti razloge njegovog korištenja u našem zadatku.

**Comment by bole188** [comment]
Ocjena težine (1 - veoma lako, 10 - veoma teško):

6

**Comment by sdejana** [comment]
Ocjena težine:

**6**

**Comment by jelena0000** [comment]
Vrijeme izrade: 100 minuta
