### ISSUE TITLE
Issue #8: Integrisanje RGB senzora, servo motora, diode i dugmeta na pločicu

### ISSUE THREAD

**Issue by bole188** [lukavidic/ColorSorter_C#8]
U okviru Issue #8 potrebno je:

- [ ] Za svaku komponentu priložiti šemu spajanja
- [ ] Utvrditi električne veze između elemenata
- [ ] Definisati potrebne zahtjeve
- [ ] Utvrditi rad sklopa sa komponentama
- [ ] Predvidjeti međuzavisnosti komponenata 
- [ ] Priložiti potrencijalne probleme sa opisom

**Comment by bole188** [comment]
Ocjena težine (1 - veoma lako, 10 - veoma teško):

5

**Comment by sdejana** [comment]
Ocjena težine:

**6**

**Comment by jelena0000** [comment]
Ocjena težine:

6

**Comment by sdejana** [comment]
Servo treba oko 100-250mA u toku rada, tj. pomijeranja.
Provjeriti koliko mikrokontroler može dati struje po pinu i ukupno.
Biće potrebno strujno pojačanje vjerovatno (provjeriti).

**Comment by sdejana** [comment]
![el_karakteristike](https://github.com/user-attachments/assets/be6c023f-25c6-4ece-bd0c-88966638e635)

**Comment by sdejana** [comment]
![Image](https://github.com/user-attachments/assets/27c14b73-1f54-43e0-845c-cbde8219e3bf)
Pojačavač, verzija no.1

**Comment by sdejana** [comment]
Color 10 Click:
Napon od 5V je potreban RGB diodi koja označava uspješno detektovanje boje.
Napon od 3.3V je za senzor boje konkretno. 
Analizirati šemu...

**Comment by sdejana** [comment]
Vrijeme provedeno pri radu: 2.5h.
