### ISSUE TITLE
Issue #9: Diskusija o realizaciji štampane pločice

### ISSUE THREAD

**Issue by bole188** [lukavidic/ColorSorter_C#9]
U okviru Issue #9 neophodno je da tim razmotri sve prethodno urađene zadatke i isplanira dalji tok dizajniranja štampane pločice. U okviru ovog zadatka vidjeti postoji li potreba za dodatnim pasivnim komponentama.

**Comment by sdejana** [comment]
Ocjena težine:

**10**

**Comment by jelena0000** [comment]
Ocjena težine: 8
